global:
  scrape_interval: 15s      # Cada 15s Prometheus va a buscar métricas
  evaluation_interval: 15s  # Cada 15s evalúa las alertas (si las configuras)

scrape_configs:
  - job_name: 'smartrestaurant-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']   # nombre del servicio en docker-compose
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'smartrestaurant-backend'
