# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: 3600000  # 1 hora en milisegundos
  refresh-token-expiration: 604800000  # 7 días en milisegundos
  issuer: smartRestaurant

# Spring Configuration
spring:
  application:
    name: smartRestaurant
  
  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:garciacamilo1970@gmail.com}
    password: ${MAIL_PASSWORD:lulf fxpj ancz ayie}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  #error:
    #include-message: always
    #include-binding-errors: always

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200,http://localhost:3000}

# Social Login Configuration
social:
  google:
    client-id: ${GOOGLE_CLIENT_ID:512756127640-hm9hitju6rp7d749v8v9tiifqj19b3ko.apps.googleusercontent.com}
    client-secret: ${GOOGLE_CLIENT_SECRET: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}
  facebook:
    app-id: ${FACEBOOK_APP_ID:}
  github:
    client-id: ${GITHUB_CLIENT_ID:}
    client-secret: ${GITHUB_CLIENT_SECRET:}

# Cloudinary Configuration
cloudinary:
  cloud_name: ${CLOUDINARY_NAME:dje3qr8tq}
  api_key: ${CLOUDINARY_KEY:693381465632364}
  api_secret: ${CLOUDINARY_SECRET:5cICFV1EvZ-E8FPCAyNSh5WGUt0}

# Multipart Configuration (para subida de imágenes)
spring.servlet.multipart:
  enabled: true
  max-file-size: 10MB
  max-request-size: 10MB