### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Crear una adición

POST http://localhost:8080/api/additions
Content-Type: application/json

{
  "name": "Papas a la francesa",
  "description": "Papas fritas cortadas en finos pedazos",
  "price": 5000
}

### Actualizar una adición

PUT http://localhost:8080/api/additions/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e
Content-Type: application/json

{
  "name": "Papitas a la francesa",
  "description": "Papas fritas cortadas en finos pedazos",
  "price": 2000
}

### Obtener el detalle por id

GET http://localhost:8080/api/additions/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e

### Eliminar una adición

DELETE http://localhost:8080/api/additions/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e

### Obtener todas las adiciones

GET http://localhost:8080/api/additions

