### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Crear un plato

POST http://localhost:8080/api/dishes/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e/categories
Content-Type: application/json

{
  "name": "Bandeja Paisa",
  "description": "Una deliciosa bandeja paisa con todos los acompañamientos",
  "price": 25000,
  "photos": ["https://example.com/plato1.jpg", "https://example.com/plato2.jpg"]
}

### Actualizar un plato

PUT http://localhost:8080/api/dishes/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e
Content-Type: application/json

{
  "name": "Bandeja Paisa",
  "description": "Una deliciosa bandeja paisa con todos los acompañamientos y mas cosas",
  "price": 28000,
  "photos": ["https://example.com/plato1.jpg", "https://example.com/plato2.jpg"]
}

### Obtener detalle de un plato

GET http://localhost:8080/api/dishes/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e

### Eliminar un plato

DELETE http://localhost:8080/api/dishes/e3fcd2cd-32cd-4955-bf1c-0a527fba1d9e

### Obtener todos los platos

GET http://localhost:8080/api/dishes/0/page

