### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Obtener todos los movimientos de inventario

GET http://localhost:8080/api/inventory/all

